### ISSUE TITLE
Fjerne versjon fra reponavn

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-elasticsearch7-config#11]
Vi hadde en periode to separate elasticsearch-podder, med forskjellige versjoner. Vi burde la denne overta det gamle repoet (fdk-elasticsearch-config), og arkivere dette.

**Comment by stigbd** [comment]
Eg forstår dette issue slik at eg skal arkivere følgande repo: fdk-elasticsearch7-config
Altså dette repoet.

**Comment by valosnah** [comment]
Ja, det enkleste er sikkert om vi arkiverer dette repoet. Jeg kan kopiere over det som trengs til fdk-elasticsearch-config, så bruker vi det videre.

**Comment by stigbd** [comment]
Lukker issue og arkiverer.
